name: sponge_remote_mobile
description: Sponge Remote Mobile.
version: 0.17.0+11

publish_to: none

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  path_provider: ^2.0.3
  flutter_local_notifications: ^8.2.0
  multicast_dns: ^0.3.1
  connectivity_plus: ^1.1.0
  network_info_plus: ^1.1.0
  permission_handler: ^8.1.6

  flutter_map: ^0.13.1
  flutter_map_location: ^0.12.0
  flutter_map_marker_cluster: ^0.4.0

  badges: ^2.0.1
  cached_network_image: ^3.1.0

  scrollable_positioned_list: ^0.1.10

  logging: ^1.0.1

  material_design_icons_flutter: 4.0.5655

  sponge_flutter_api: ^0.17.0
  sponge_client_dart: ^1.17.0
  sponge_grpc_client_dart: ^1.17.0

dependency_overrides:
  # Use the local library if possible.
  sponge_client_dart:
    path: ../../sponge_client_dart
  sponge_grpc_client_dart:
    path: ../../sponge_grpc_client_dart
  sponge_flutter_api:
    path: ../../sponge_flutter_api
  sponge_remote:
    path: ../sponge_remote

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  test: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  image_path_ios: "assets/images/icon_ios.png"
  adaptive_icon_background: "#FFE9C382"
  adaptive_icon_foreground: "assets/images/icon_android.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/images/logo.png
    - assets/images/banner.png
    - assets/images/icon.png
    - assets/images/icon_small.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
